# ==============================================================================
# Configuración de GoReleaser para Cifratin
# ==============================================================================
version: 2
project_name: cifratin

before:
  hooks:
    - go mod tidy

builds:
  - id: cifratin-cli
    binary: cifratin
    main: ./cmd/cifratin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: cifratin-grpc-client
    binary: cifratin-grpc-client
    main: ./cmd/cifratin-grpc-client
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: cifratin-grpc-server
    binary: cifratin-grpc-server
    main: ./cmd/cifratin-grpc-server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: cifratin-http-server
    binary: cifratin-http-server
    main: ./cmd/cifratin-http-server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

  - id: cifratin-http-client
    binary: cifratin-http-client
    main: ./cmd/cifratin-http-client
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    # Usar zip para sistemas operativos Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
