// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: api/proto/v1/cifratin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileRequest representa una petición para cifrar o descifrar.
type FileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Datos crudos a procesar.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Contraseña a partir de la cual se derivará la clave criptográfica.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_api_proto_v1_cifratin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cifratin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cifratin_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// FileResponse representa el resultado del cifrado o descifrado.
type FileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Datos procesados resultantes.
	ProcessedData []byte `protobuf:"bytes,1,opt,name=processed_data,json=processedData,proto3" json:"processed_data,omitempty"`
	// Mensaje de estado.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_api_proto_v1_cifratin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_cifratin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_cifratin_proto_rawDescGZIP(), []int{1}
}

func (x *FileResponse) GetProcessedData() []byte {
	if x != nil {
		return x.ProcessedData
	}
	return nil
}

func (x *FileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_cifratin_proto protoreflect.FileDescriptor

const file_api_proto_v1_cifratin_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/cifratin.proto\x12\vcifratin.v1\"=\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"O\n" +
	"\fFileResponse\x12%\n" +
	"\x0eprocessed_data\x18\x01 \x01(\fR\rprocessedData\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x99\x01\n" +
	"\x0fCifratinService\x12B\n" +
	"\vEncryptFile\x12\x18.cifratin.v1.FileRequest\x1a\x19.cifratin.v1.FileResponse\x12B\n" +
	"\vDecryptFile\x12\x18.cifratin.v1.FileRequest\x1a\x19.cifratin.v1.FileResponseB+Z)github.com/sehogas/cifratin/pkg/api/v1;v1b\x06proto3"

var (
	file_api_proto_v1_cifratin_proto_rawDescOnce sync.Once
	file_api_proto_v1_cifratin_proto_rawDescData []byte
)

func file_api_proto_v1_cifratin_proto_rawDescGZIP() []byte {
	file_api_proto_v1_cifratin_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_cifratin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_cifratin_proto_rawDesc), len(file_api_proto_v1_cifratin_proto_rawDesc)))
	})
	return file_api_proto_v1_cifratin_proto_rawDescData
}

var file_api_proto_v1_cifratin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_cifratin_proto_goTypes = []any{
	(*FileRequest)(nil),  // 0: cifratin.v1.FileRequest
	(*FileResponse)(nil), // 1: cifratin.v1.FileResponse
}
var file_api_proto_v1_cifratin_proto_depIdxs = []int32{
	0, // 0: cifratin.v1.CifratinService.EncryptFile:input_type -> cifratin.v1.FileRequest
	0, // 1: cifratin.v1.CifratinService.DecryptFile:input_type -> cifratin.v1.FileRequest
	1, // 2: cifratin.v1.CifratinService.EncryptFile:output_type -> cifratin.v1.FileResponse
	1, // 3: cifratin.v1.CifratinService.DecryptFile:output_type -> cifratin.v1.FileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_cifratin_proto_init() }
func file_api_proto_v1_cifratin_proto_init() {
	if File_api_proto_v1_cifratin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_cifratin_proto_rawDesc), len(file_api_proto_v1_cifratin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_cifratin_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_cifratin_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_cifratin_proto_msgTypes,
	}.Build()
	File_api_proto_v1_cifratin_proto = out.File
	file_api_proto_v1_cifratin_proto_goTypes = nil
	file_api_proto_v1_cifratin_proto_depIdxs = nil
}
