// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.2
// source: api/proto/v1/cifratin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CifratinService_EncryptFile_FullMethodName = "/cifratin.v1.CifratinService/EncryptFile"
	CifratinService_DecryptFile_FullMethodName = "/cifratin.v1.CifratinService/DecryptFile"
)

// CifratinServiceClient is the client API for CifratinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CifratinService provee métodos gRPC para cifrar y descifrar archivos.
type CifratinServiceClient interface {
	// EncryptFile cifra un archivo.
	EncryptFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error)
	// DecryptFile descifra un archivo.
	DecryptFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error)
}

type cifratinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCifratinServiceClient(cc grpc.ClientConnInterface) CifratinServiceClient {
	return &cifratinServiceClient{cc}
}

func (c *cifratinServiceClient) EncryptFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, CifratinService_EncryptFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cifratinServiceClient) DecryptFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, CifratinService_DecryptFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CifratinServiceServer is the server API for CifratinService service.
// All implementations must embed UnimplementedCifratinServiceServer
// for forward compatibility.
//
// CifratinService provee métodos gRPC para cifrar y descifrar archivos.
type CifratinServiceServer interface {
	// EncryptFile cifra un archivo.
	EncryptFile(context.Context, *FileRequest) (*FileResponse, error)
	// DecryptFile descifra un archivo.
	DecryptFile(context.Context, *FileRequest) (*FileResponse, error)
	mustEmbedUnimplementedCifratinServiceServer()
}

// UnimplementedCifratinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCifratinServiceServer struct{}

func (UnimplementedCifratinServiceServer) EncryptFile(context.Context, *FileRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptFile not implemented")
}
func (UnimplementedCifratinServiceServer) DecryptFile(context.Context, *FileRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptFile not implemented")
}
func (UnimplementedCifratinServiceServer) mustEmbedUnimplementedCifratinServiceServer() {}
func (UnimplementedCifratinServiceServer) testEmbeddedByValue()                         {}

// UnsafeCifratinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CifratinServiceServer will
// result in compilation errors.
type UnsafeCifratinServiceServer interface {
	mustEmbedUnimplementedCifratinServiceServer()
}

func RegisterCifratinServiceServer(s grpc.ServiceRegistrar, srv CifratinServiceServer) {
	// If the following call panics, it indicates UnimplementedCifratinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CifratinService_ServiceDesc, srv)
}

func _CifratinService_EncryptFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CifratinServiceServer).EncryptFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CifratinService_EncryptFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CifratinServiceServer).EncryptFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CifratinService_DecryptFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CifratinServiceServer).DecryptFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CifratinService_DecryptFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CifratinServiceServer).DecryptFile(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CifratinService_ServiceDesc is the grpc.ServiceDesc for CifratinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CifratinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cifratin.v1.CifratinService",
	HandlerType: (*CifratinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptFile",
			Handler:    _CifratinService_EncryptFile_Handler,
		},
		{
			MethodName: "DecryptFile",
			Handler:    _CifratinService_DecryptFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/cifratin.proto",
}
